spring.application.name=cart-service

spring.datasource.url=jdbc:mysql://localhost:3306/revshop_db
spring.datasource.username=root
spring.datasource.password=Rutu1234@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
product.service.url=http://localhost:8082
server.port=8083